### ISSUE TITLE
Filter "Wert von/bis" filtert nicht

### ISSUE THREAD

**Issue by xantippe** [MetaModels/filter_fromto#10]
Filter "Wert von/bis" filtert nicht

TNG dev-master (7efaa8b3) 

siehe https://community.contao.org/de/showthread.php?60034-von-bis-filter-funktioniert-nicht&p=390721&viewfull=1#post390721

**Comment by discordier** [comment]
According to you forum post, everything is ok up to `FromTo::getMatchingIds()`, so what exactly is then the problem in filtering?

**Comment by xantippe** [comment]
MM a10 + DCG b34 + Filter FT a2

soweit o.k.

![shot114](https://cloud.githubusercontent.com/assets/1045318/13188434/dcb234c2-d751-11e5-9ee8-aaddf7e0eb04.jpg)

::::::::::::::::::::::::::

![shot115](https://cloud.githubusercontent.com/assets/1045318/13188440/e59282d6-d751-11e5-9dba-0e26ea20ca1c.jpg)
