### ISSUE TITLE
filtert nur numerische Werte

### ISSUE THREAD

**Issue by haendersonfox** [MetaModels/filter_fromto#12]
keine Dezimalen Werte...

**Comment by discordier** [comment]
Mehr details?
Wie konfiguriert?
Was machst du?
Was erwartest du?
Was passiert statt dessen?

"filtert nicht" ist einfach zu ungenau

**Comment by xantippe** [comment]
MM a10 + DCG b34 + Filter FT a2

Dezimalwerte werden nicht gefiltert - es werden keine Items ausgegeben

![shot117](https://cloud.githubusercontent.com/assets/1045318/13188749/aa4e7df4-d753-11e5-8736-79e3de9d5817.jpg)

:::::::::::::::::::::::::

![shot116](https://cloud.githubusercontent.com/assets/1045318/13188755/b29b261a-d753-11e5-9893-575f59d11837.jpg)

**Comment by discordier** [comment]
Das koennte sein.

**Comment by discordier** [comment]
Sollte mit den folgenden commits gefixt sein:
MetaModels/attribute_decimal@27071dd
MetaModels/attribute_numeric@071e919

**Comment by xantippe** [comment]
test mit
* DCG dev-hotfix/2.0.0-beta34 (bb67abb3)
* MM core dev-hotfix-2.0.0-alpha10 (759c9997)
* attribute_decimal dev-hotfix-2.0.0-alpha4 (8589c1a1)

geht **nicht**

![shot146](https://cloud.githubusercontent.com/assets/1045318/13494519/1200fb48-e145-11e5-9d20-387b5244b541.jpg)

![shot147](https://cloud.githubusercontent.com/assets/1045318/13494525/199f3b3a-e145-11e5-8cb9-300cfea14968.jpg)

**Comment by discordier** [comment]
I can not reproduce this in tests... I really wonder what is going on here.

**Comment by xantippe** [comment]
muss ich noch was aktualisieren als die drei Pakete?

**Comment by discordier** [comment]
eigentlich nicht

**Comment by xantippe** [comment]
hmm.. wo kann man für "debug" ansetzen?

**Comment by xantippe** [comment]
ich habe in https://github.com/MetaModels/attribute_decimal/blob/27071dd274ce696e578eb66862126fd21c926d6b/src/MetaModels/Attribute/Decimal/Decimal.php#L79-L103

ein "print_r" eingestreut - auf der FE Seite wird alles wie gewohnt angezeigt ohne Abbruch durch die()

```diff
    public function searchFor($strPattern)
    {
+      print_r($strPattern); die();
        // If search with wildcard => parent implementation with "LIKE" search.
        if (false !== strpos($strPattern, '*') || false !== strpos($strPattern, '?')) {
            return parent::searchFor($strPattern);
        }
        // Not with wildcard but also not numeric, impossible to get decimal results.
        if (!is_numeric($strPattern)) {
            return array();
        }

        // Do a simple search on given column.
        $query = $this->getMetaModel()->getServiceContainer()->getDatabase()
            ->prepare(
                sprintf(
                    'SELECT id FROM %s WHERE %s=?',
                    $this->getMetaModel()->getTableName(),
                    $this->getColName()
                )
            )
            ->execute($strPattern);

        return $query->fetchEach('id');
    }
```

**Comment by xantippe** [comment]
PR für Filter & Decimal erstellt: https://github.com/xantippe/attribute_decimal/commit/681e0a3330740eb5f4dd23a37a5d70b7d3902093

**Comment by discordier** [comment]
decimal wurde gemerget, ich denke damit kann das nun zu

**Comment by xantippe** [comment]
ja - num hatte ich ja auch nochmal getestet https://github.com/MetaModels/attribute_numeric/commit/071e919#commitcomment-16493208
