### ISSUE TITLE
filtert nicht korrekt, wenn nur der bis-wert ausgewählt ist...

### ISSUE THREAD

**Issue by haendersonfox** [MetaModels/filter_fromto#13]
ich habe ein select "von" und ein select "bis"

wähle ich nun "bis" aus, was als wert eigentlich reichen sollte, filtert er nicht korrekt…
ich muss mir damit helfen, dass ich beim select einen value="" setze… sowohl bei "von" als auch bei "bis".

**Comment by xantippe** [comment]
vielleicht hängt es damit zusammen... https://github.com/MetaModels/filter_fromto/issues/10

**Comment by xantippe** [comment]
MM a10 + DCG b34 + Filter FT a2

* Daten:
![shot114](https://cloud.githubusercontent.com/assets/1045318/13189159/04eb0f96-d756-11e5-8701-3a05868ecced.jpg)

* von-bis: korrekt
![shot115](https://cloud.githubusercontent.com/assets/1045318/13189179/19831674-d756-11e5-9d7e-64423330b9da.jpg)


* von-*: korrekt
![shot116](https://cloud.githubusercontent.com/assets/1045318/13189182/1e57ab4c-d756-11e5-9a9b-8ac5511ef365.jpg)


* *-bis: falsch
![shot117](https://cloud.githubusercontent.com/assets/1045318/13189185/23bdb464-d756-11e5-91d6-6ddd83958a4d.jpg)

**Comment by discordier** [comment]
Dein Filtersetting beinhaltet NUR den von-bis?

**Comment by xantippe** [comment]
In dem Filterset hatte ich mehrere von-bis-Filterregeln zum testen - jedoch immer nur eine Regel aktiv...

**Comment by discordier** [comment]
Aktiv im Sinne von "Auge an" oder eingegeben?
Bitte immer minimale test cases bauen. :)

**Comment by xantippe** [comment]
Aktiv im Sinne von "Auge grün"... hier nochmal die Einstellunegn + Ausgabe

![shot128](https://cloud.githubusercontent.com/assets/1045318/13312619/73f9779c-db98-11e5-9dce-ed99e72523cb.jpg)

:::::::::::::::::::::::::::::::
![shot129](https://cloud.githubusercontent.com/assets/1045318/13312625/7e98518c-db98-11e5-9f47-91dece3b4308.jpg)

:::::::::::::::::::::::::::::::
![shot130](https://cloud.githubusercontent.com/assets/1045318/13312630/8571a8dc-db98-11e5-90a9-7579bc56014a.jpg)

**Comment by poldip** [comment]
Hallo zusammen - genauso verhält es sich bei mir auch. Ein leeres "von"-Feld liefert das gleiche Ergebnis wie ein leeres "bis"-Feld. Gibt es hier schon irgendetwas Neues?

**Comment by xantippe** [comment]
getestet mit dev-hotfix/2.0.0-alpha3 7764d77 => o.k.

![shot138](https://cloud.githubusercontent.com/assets/1045318/13489434/4d780c2a-e127-11e5-8b30-a2b8ece88536.jpg)

![shot137](https://cloud.githubusercontent.com/assets/1045318/13489441/547e9368-e127-11e5-83c1-c262d1e8cddd.jpg)

**Comment by poldip** [comment]
hm - ok (?) und was muss ich jetzt machen, damit es funktioniert?

**Comment by xantippe** [comment]
warten oder dev-hotfix/2.0.0-alpha3 einspielen (siehe MM-Handbuch)
