### ISSUE TITLE
keine Fehlermeldung im FE bei Filter nach Datum, wenn Eingabeformat nicht korrekt

### ISSUE THREAD

**Issue by xantippe** [MetaModels/filter_fromto#14]
im Filter ist bei Schema "Datum" und bei Format "d.m.Y" eingetragen (siehe https://github.com/MetaModels/filter_fromto/issues/9#issuecomment-186389532) - wird dennoch z.B. 2011 eingeben kommt keine Fehlermeldung und es wird nicht nach dem Wert gefiltert

![shot113](https://cloud.githubusercontent.com/assets/1045318/13188221/4293f35e-d750-11e5-944b-b1b41bbb6be9.jpg)

**Comment by discordier** [comment]
Ok, this is evil. We somehow need to display the widget error in there. However, the widget gets generated way too late for this...
Will have to dive into this some more

**Comment by xantippe** [comment]
Zusatzfrage: wenn ich nichts eintrage, werden dann die Vorgaben "kaskadierend" bei den Einstellungen des "Startpunkt einer Webseite" bzw. Systemeinstellungen abgefragt? 

und... wie ist es bei mehrsprachigen MMs? gibt es dann für jede Sprache ein Eingabefeld?

**Comment by discordier** [comment]
?

**Comment by xantippe** [comment]
ich kann für das Eingabefeld eine date()-Formatierung eingeben - wie z.B. ```d.m.Y``` - für DACH wäre das o.k., jedoch für EN wäre ```m\d\Y``` die "Standardformatierung"...

wenn man den Filter auf verschiedenen Seitenbäumen von Contao ausgeben lässt, stehen die Formatierungen aus "Startpunkt einer Webseite" zur Verfügung bzw. als "Fallback" die aus der Systemeinstellung - die könnten abgefragt werden, wenn in dem Feld nichts eingetragen ist...

**Comment by xantippe** [comment]
getestet mit dev-hotfix/2.0.0-alpha3 7764d77 => o.k.

![shot139](https://cloud.githubusercontent.com/assets/1045318/13489414/2afcfe26-e127-11e5-9e51-fbbca1ca9d1e.jpg)
