### ISSUE TITLE
the rule fails if the date format is not specified

### ISSUE THREAD

**Issue by zonky2** [MetaModels/filter_fromto#16]
the rule fails if the date format is not specified

**Comment by richardhj** [comment]
What does "fail" mean?

**Comment by zonky2** [comment]
without doesn´t found any items - with date format found any...

**Comment by stefanheimes** [comment]
The system has 3 levels. First is the format which is entered by the filter configuration. The second one is the format from the page and after this the settings from contao. So you have 3 possible entry points to add the format.

**Comment by stefanheimes** [comment]
So it's normal if you are on a page with german forman but didn't have any format specify, the system can't translate the string to a timestamp. So it's not a bug, you just have to define one of the three points to get ther right function. Any question. If not can we close this issue?

**Comment by zonky2** [comment]
you are right...
