### ISSUE TITLE
Date Filter lower/upper bound. 

### ISSUE THREAD

**Issue by stefanheimes** [MetaModels/filter_fromto#22]
See 599bbff88075572a92f5fac2093097ae8ac12de1

Okay i've make a mistake. Instead of creating a PR i pushed it into the hotfix brunch. So we have to discuss this here. 

We have talk abount the date filter. The filter used semi random times for the houres, minutes and seconds. With this commit, the lower bound will be set to 0h 0m 0s. The upper bound will be set to 23h, 59m, 59s. 

So this fix should solve the problem where some entries could not be find becouse the time wasn't set proberly. 

@discordier Did i broke something again?
@zonky2 Can you take a look intio this and test it. For my test everything works.

**Comment by zonky2** [comment]
see https://github.com/MetaModels/filter_fromto/commit/599bbff88075572a92f5fac2093097ae8ac12de1
