### ISSUE TITLE
add placeholder for date or datim format

### ISSUE THREAD

**Issue by zonky2** [MetaModels/filter_fromto#24]
add placeholder for date or datim format

**Comment by discordier** [comment]
Can you elaborate?

What is the current behaviour?

What do you suggest to add?

**Comment by zonky2** [comment]
look at Screenshot http://easycaptures.com/fs/uploaded/1167/8136617773.png

you could make a checkbox so that the set date or Tadum time format is displayed as placeholder + a text field for a free input

**Comment by discordier** [comment]
Adding screenshot here for persistency:
![8136617773](https://user-images.githubusercontent.com/940331/54054399-5a9e7e80-41ea-11e9-9174-685670a1c6ca.png)

So you want a placeholder attribute on the HTML input field, now I understand.

**Comment by zonky2** [comment]
in MM 2.2 implemented
