### ISSUE TITLE
Fehler MM 2.1

### ISSUE THREAD

**Issue by SGehle** [MetaModels/filter_fromto#25]
Seit dem letzten Composer Update funktioniert das Bundle nicht mehr. Installiert für MetaModels 2.1 - Version dev-release/2.1.0
(8.3.2019, 20:15:53)

Error thrown while running command "cache:warm  
  up --env=prod". Message: "Too few arguments to function MetaModels\FilterFr  
  omToBundle\FilterSetting\FromToFilterSettingTypeFactory::__construct(), 0 p  
  assed in /var/www/var/cache/prod/ContainerIszsm  
  5u/getMetamodels_FilterSettingFactoryService.php on line 16 and exactly 2 e  
  xpected" ["exception" => ArgumentCountError { …},"command" => "cache:warmup  
   --env=prod","message" => "Too few arguments to function MetaModels\FilterF  
  romToBundle\FilterSetting\FromToFilterSettingTypeFactory::__construct(), 0   
  passed in /var/dev/var/cache/prod/ContainerIszs  
  m5u/getMetamodels_FilterSettingFactoryService.php on line 16 and exactly 2   
  expected"]                                                                   
                                                                               
  In FromToFilterSettingTypeFactory.php line 54:                               
                                                                               
                                                                               
    Type error: Too few arguments to function MetaModels\FilterFromToBundle\F  
  il                                                                           
    terSetting\FromToFilterSettingTypeFactory::__construct(), 0 passed in /va  
  r/                                                                           
    www/cache/prod/ContainerIszsm5u/getMetamo  
  de                                                                           
    ls_FilterSettingFactoryService.php on line 16 and exactly 2 expected

**Comment by zonky2** [comment]
change

```diff
    metamodels.filter_fromto.factory:
        class: MetaModels\FilterFromToBundle\FilterSetting\FromToFilterSettingTypeFactory
+        arguments:
+          - '@event_dispatcher'
+          - '@MetaModels\Filter\FilterUrlBuilder'
        tags:
          - { name: metamodels.filter_factory }
```
in https://github.com/MetaModels/filter_fromto/blob/release/2.1.0/src/Resources/config/services.yml#L2-L5

**Comment by zonky2** [comment]
fixed https://github.com/MetaModels/filter_fromto/commit/d3dca1674f7cf59d9f452fe3366d415ec6aa99b4
