### ISSUE TITLE
[tng] missing colname in template

### ISSUE THREAD

**Issue by Zeromax** [MetaModels/filter_fromto#6]
The colname of the fromTo is missing in the template.

I have added it here, but it does not fit the problem:
https://github.com/MetaModels/filter_fromto/blob/tng/src/system/modules/metamodelsfilter_fromto/MetaModels/Filter/Setting/FromTo.php#L226

```php
'colname'   => $objAttribute->getColname(),
```

**Comment by discordier** [comment]
The colname has been introduced.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@Zeromax could you please have a final look at this and tell if your issue has been resolved?
