### ISSUE TITLE
Datum von/bis filtert erst ab dem Folgetag

### ISSUE THREAD

**Issue by andre5tz** [MetaModels/filter_fromto#9]
Hallo,
habe es endlich geschafft den Filter "Wert von/bis für ein Datum" zum Laufen zu bringen.

Kann es sein, dass der Filter "von" für den 1. Wert nicht korrekt funktioniert?

Bsp.: Wenn die Auswahl im Frontend vom 02.11.2015 bis 05.11.2015 eingestellt wird, dann werden alle Einträge vom 03.11.2015 bis zum 05.11.2015 gezeigt. Einträge vom 02.11.2015 fehlen.

VG
André

**Comment by discordier** [comment]
Dazu gibt es die Einstellung inklusive/exclusive

**Comment by andre5tz** [comment]
Sorry, wenn ich nochmal nachfragen muss. Ich habe jetzt so ziemlich alles durchgeklickt, aber ein inklusive/exclusive habe ich nicht gefunden?
Ich hätte die Einstellung ja am ehesten bei den Filtereinstellungen erwartet, nur da ist bei mir nix :-(
Im Modul Metamodel-Frontendfilter auch nicht.

Habe vor dem Suchen extra nochmal ein Update in der Paketverwaltung durchgeführt. 
Hoffe die richtigen Versionen genommen zu haben.
metamodels/core	dev-master (62b5de39)
metamodels/bundle_all	1.0.1
contao-community-alliance/dc-general	dev-develop (6ad3357a)

**Comment by discordier** [comment]
In den Einstellung des filter settings:
DE: "Wert 1 einfügen" == "'Value 1 included'" ==> "von Wert ist inclusive"
DE: "Wert 2 einfügen" == "'Value 2 included'" ==> "bis Wert ist inclusive"

@xantippe Da sollten wir glaub nochmal an die Sprachdateien. :dog:

**Comment by xantippe** [comment]
o.k. - sehe ich mir nochmal an...

**Comment by xantippe** [comment]
@discordier: Transifex geändert!

**Comment by discordier** [comment]
@andre5tz Wenn dein Problem damit behoben ist, dann bitte schliessen.

**Comment by andre5tz** [comment]
So sieht mein Filter aktuell aus, nur um sicherzustellen, dass wir von der gleichen Einstellung reden.
Ein Update über Composer ist ausgeführt.
![filter-fromto](https://cloud.githubusercontent.com/assets/2168409/11094813/2a77e13e-8892-11e5-9ce8-6c17694b0977.jpg)

DE: [x] Wert 1 einfügen  [x] Feld für Wert 1
DE: [x] Wert 2 einfügen  [x] Feld für Wert 2

Alle 4 Werte ausgewählt - Problem besteht weiterhin.

DE: [x] Wert 1 einfügen  [  ] Feld für Wert 1
DE: [x] Wert 2 einfügen  [x] Feld für Wert 2

Nehme ich den Haken bei "Feld für Wert 1" oder "Feld für Wert 2" raus, kommt die Folgende Fehlermeldung:

Fatal error: Uncaught exception LengthException with message Only one value is allowed. thrown in composer/vendor/metamodels/filter_fromto/src/MetaModels/Filter/Setting/AbstractFromTo.php on line 332

#0 composer/vendor/metamodels/core/src/MetaModels/Filter/Setting/Collection.php(132): MetaModels\Filter\Setting\AbstractFromTo->prepareRules(Object(MetaModels\Filter\Filter), Array)
#1 composer/vendor/metamodels/core/src/MetaModels/Filter/Setting/Collection.php(197): MetaModels\Filter\Setting\Collection->addRules(Object(MetaModels\Filter\Filter), Array)
#2 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/FrontendFilter.php(288): MetaModels\Filter\Setting\Collection->getParameterFilterWidgets(Array, Array, Object(MetaModels\FrontendIntegration\FrontendFilterOptions))
#3 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/FrontendFilter.php(78): MetaModels\FrontendIntegration\FrontendFilter->getFilters()
#4 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/HybridFilterBlock.php(129): MetaModels\FrontendIntegration\FrontendFilter->getMetaModelFrontendFilter(Object(MetaModels\FrontendIntegration\Module\Filter))
#5 system/modules/core/classes/Hybrid.php(231): MetaModels\FrontendIntegration\HybridFilterBlock->compile()
#6 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/MetaModelHybrid.php(102): Contao\Hybrid->generate()
#7 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/HybridFilterBlock.php(118): MetaModels\FrontendIntegration\MetaModelHybrid->generate()
#8 system/modules/core/elements/ContentModule.php(59): MetaModels\FrontendIntegration\HybridFilterBlock->generate()
#9 system/modules/core/library/Contao/Controller.php(476): Contao\ContentModule->generate()
#10 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#11 system/modules/tags/modules/ModuleArticle.php(41): Contao\ModuleArticle->compile()
#12 system/modules/core/modules/Module.php(282): Aurealis\ModuleArticle->compile()
#13 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#14 system/modules/core/library/Contao/Controller.php(409): Contao\ModuleArticle->generate(false)
#15 system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#16 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#17 system/modules/core/controllers/FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#18 index.php(20): Contao\FrontendIndex->run()
#19 {main}

Nehme ich beide Haken für "Wert für Feld 1 und Feld 2" raus, dann erscheint nur noch ein Auswahlfeld. Der Filter hat dann anscheinend keine Auswirkungen mehr.

Insgesamt verhält sich die Einstellung nicht so, wie ich es erwarten würde. Muss ich evtl. nochmal genauer und in Ruhe testen. Vielleicht könnt Ihr das Verhalten aber auch bestätigen.
Ich kann aber auch gerne mal einen Zugang freischalten, falls Ihr es Euch selbst anschauen möchtet.

**Comment by discordier** [comment]
I really can not reproduce this...
Maybe you can shed some light what exactly your configuration is.

@xantippe could you have a look on this one?

**Comment by xantippe** [comment]
Test mit MM a10 und DCG b34

* keine Fehlermeldung
* korrekt gefiltert

![shot111](https://cloud.githubusercontent.com/assets/1045318/13187951/b70f485c-d74e-11e5-84a7-6fc7c6cd27e8.jpg)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
![shot112](https://cloud.githubusercontent.com/assets/1045318/13187970/cdb54746-d74e-11e5-8944-cab2cb184091.jpg)

**Comment by design23** [comment]
Hi,
ich habe aktuell den gleichen Effekt wie ihn andre5tz im ersten Post beschreibt.
Der eingetragene Wert 1 wird nicht einbezogen, obwohl das entsprechende Häkchen gesetzt ist.

contao/core                                             --> 3.5.24
metamodels/bundle_all                           --> 2.0.0
metamodels/core                                    --> dev-hotfix/alpha-15 (46370fb8)
contao-community-alliance/dc-general  -- > dev-hotfix/beta-39 (06bcb3b1)

**Comment by zonky2** [comment]
* welche Einstellungen des Filters (ggf. Screenshot)
* welcher (Timestamp) Wert in DB? -  ggf. Zeitzonen-Problem
* welcher Wert in FE-Filter?
* Seite irgendwo im Netz?

**Comment by design23** [comment]
- Einstellungen identisch zu deinem letzten Screenshot
- Timestamp in DB: 1491135164
- Wert im FE-Filter: 02.04.2017
- leider nein

**Comment by zonky2** [comment]
kannst Du das an der Stelle https://github.com/MetaModels/filter_fromto/blob/master/src/MetaModels/Filter/Rules/FromToDate.php#L68 mal debuggen?

**Comment by design23** [comment]
Heute leider nicht mehr am Rechner. Mache das dann morgen und melde mich dann.

**Comment by design23** [comment]
Wie kann ich das debuggen?

**Comment by zonky2** [comment]
kannst du auf Mumble kommen?

**Comment by design23** [comment]
Heute leider nicht mehr... Morgen evtl.?

**Comment by zonky2** [comment]
o.k. - kannst mir im Forum auch per PN Deinen Skypenamen senden

**Comment by design23** [comment]
Ich glaube wir können uns die Debug-Session sparen.
Habe den Filter mal gelöscht und komplett neu angelegt – jetzt scheint es korrekt zu arbeiten.
Ich habe zwar absolut NICHTS anders gemacht oder eingestellt, aber diesmal wird der eingetragene Wert definitiv mit einbezogen...

**Comment by zonky2** [comment]
;-)

**Comment by zonky2** [comment]
irgendwas haut da nicht hin... die Filterungen "spielen verrückt"

**Comment by zonky2** [comment]
mit "aktuellem MM" getestet - Wert einbeziehen funktioniert nicht korrekt => muss nochmal genauer untersucht werden...

**Comment by zonky2** [comment]
Das Problem ist, dass beim Speichern eines Datums auch die aktuelle Uhrzeit abgespeichert wird und dadurch der Timestamp "nicht stimmt" - dito beim Eingeben des Datums für die Filterung...

Prüfen kann man das mit der Aus- und Eingabe der Uhrzeit `d.m.Y H:i:s`

Aktueller Workaround: die Timestamps in der Datenbank auf Uhrzeit `00:00:00` setzen.

An einer Lösung wird gearbeitet...

**Comment by pliou** [comment]
Datei: FromToDate.php
Zeile 134:
                $this->setUpperBound(($timestamp - (($timestamp % 86400) - (86400 - 1))), $this->isUpperInclusive());

Löst dies das Problem nicht?

**Comment by discordier** [comment]
Bumped to 2.2 for the moment, maybe we fit it into 2.1 but definitely not into 2.0

**Comment by discordier** [comment]
Was implemented in 599bbff88075572a92f5fac2093097ae8ac12de1 (2.0.2)

**Comment by discordier** [comment]
After discussion with @zonky2, this is implemented as needed.

**Comment by marcoheinz** [comment]
Gibt es dazu irgendwelche Neuigkeiten? Problem besteht weiterhin in 2.2!

**Comment by zonky2** [comment]
in MM 2.2 kann man in den Einstellungen des Attributes in der Eingabemaske einstellen ob Zeit oder Datum vom Timestamp "abgeschnitten" werden soll - siehe HB https://metamodels.readthedocs.io/de/latest/manual/new-in-mm-22.html

**Comment by marcoheinz** [comment]
Wenn man in der Eingabemaske die Möglichkeit hat, die Zeit vom Timestamp "abzuschneiden", müsste man doch auch dem Filter von / bis vorgeben können wie der TS abgespeichert wird?  So kann der "nur" als Datum abgespeicherte TS ja nicht vernünftig gefiltert werden. Der Filter ist ja dazu gedacht ein Datum zu filtern und nicht die Zeit...

**Comment by zonky2** [comment]
siehe https://github.com/MetaModels/filter_fromto/issues/9#issuecomment-285422808
